### PR TITLE
73 refactor structures

### LINKED ISSUE #73: Refactor structures
Refactor structures to be instantiated using factories.

### PR DESCRIPTION
**Pull request by Matte02**
## Summary
Added structure factory and made instantiation of structures use the factory.

## Test Coverage
image
imageimage

## Diagrams
com thebois models world
com thebois models world structures

Closes #73

### CODE REVIEW

**Review by martinjonsson01 — CHANGES_REQUESTED** [review]
You missed the coverage screenshot for the `models` package, but otherwise looks good!

Only thing I really want changed before approving is making the `House` class itself package private. The rest is just minor stuff.

**Review by martinjonsson01 — APPROVED** [review]
Looks good! 👍

**Comment by martinjonsson01** [comment]
What irks me is that overall line coverage is down from 591 to 589. If you look in #76 then coverage is still 100%. I wonder what changed?

**Comment by Matte02** [comment]
> What irks me is that overall line coverage is down from 591 to 589. If you look in #76 then coverage is still 100%. I wonder what changed?

image
image

This is super weird since it's being tested here:
image
and now here:
image

**Comment by martinjonsson01** [comment]
>it's being tested here

Isn't it also being tested through the factory tests?

**Comment by martinjonsson01** [comment]
>Noticed that a lot of tests needed to be changed, is that a code smell?

Yeah, it was because we used the constructors directly (like we do with world and world tests). So the smell is actually what is being resolved in this PR, so in the future, refactors (of structures) shouldn't have to modify all the tests like we had to do this time.

**Pull request merged**
